### ISSUE TITLE
native extensions do not build on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by dpickett** [knu/ruby-unf#11] opened 2015-04-09 01:56 UTC
I was supporting @syzygy333 when he discovered a blocking error in installing `unf`

```no-highlight
➜  ~  gem install unf
Building native extensions.  This could take a while...
ERROR:  Error installing unf:
	ERROR: Failed to build gem native extension.

    /opt/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20150408-2004-b0vn44.rb extconf.rb
checking for main() in -lstdc++... yes
checking for ruby/encoding.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling unf.cc
In file included from unf.cc:1:
In file included from ./unf/normalizer.hh:4:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:265:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__bit_reference:15:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
1 error generated.
make: *** [unf.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/dpickett/.gem/ruby/2.2.1/gems/unf_ext-0.0.6 for inspection.
Results logged to /Users/dpickett/.gem/ruby/2.2.1/extensions/x86_64-darwin-14/2.2.0-static/unf_ext-0.0.6/gem_make.out
```

I've confirmed this error for ruby versions `2.2.1` and `2.0.0-p576` - for kicks I attempted a reinstall of ruby version 2.2.1 but still had no luck.

**Comment by JamesChevalier** [comment] 2015-04-13 18:28
I just ran across this while trying to reinstall [mailcatcher](http://mailcatcher.me/) in ruby 2.2.2. I was able to reproduce the problem with other ruby versions, too (2.1.5, 2.1.6, and 2.2.1).

I'm wondering if the problem could be related to my recent OS X upgrade to 10.10.3... I've tried a few things, so far - none of which have helped or changed anything:

- Installed the latest Command Line Tools
- Reinstalled the `apple-gcc42` package in homebrew
- Installed `gcc5` via homebrew (a long shot based on other gcc* packages being present)
- Removed all `gcc*` homebrew packages that were present (another long shot)

**Comment by JamesChevalier** [comment] 2015-04-13 19:25
OK, I just figured out a fix for my similar issue ... Just in case it's helpful - I had to install `Command Line Tools (OS X 10.10) for Xcode - Xcode 6.2` from the Download for Apple Developers page ... the version for Xcode 6.3 did not work for me.

**Comment by knu** [comment] 2015-04-13 20:14
Somehow I couldn't reproduce this, but a quick search gave me this: http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3
It indicates there might be something broken in Xcode 6.3 Command Line Tools.

By the way, you are filing an issue to the wrong place.  ruby-unf is not a native extension, but ruby-unf_ext is.

**Comment by duerst** [comment] 2015-04-15 00:56
Please note that as of Ruby 2.2, Unicode normalization is available directly on String from the standard library. See https://bugs.ruby-lang.org/issues/10084. The same implementation (although slightly different interface) is also available for older Rubies with the https://rubygems.org/gems/camertron-eprun gem. This originally comes from https://github.com/duerst/eprun. It's all native Ruby code, but very fast anyway.

**Comment by knu** [comment] 2015-04-20 07:04
Closing this, the error log obviously says it is about ruby-unf.

If you have additional information, please post it to knu/ruby-unf_ext#10.

**Closed by knu** 2015-04-20 07:04 UTC
